package:
  name: "giuse-py"
  version : "1.0"

source:
  git_rel : "v.1.0"
  git_url : https://github.com/gambu94/giuse-py.git

requirements:
  host:
    - python
  run:
    - python

about:
  home: https://me.com
  license: BSD2
  license_family: BSD2
  summary: First Test to Build and Upload a conda package to AnacondaCloud

